version: "3.9"

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    environment:
      - WEAVIATE_HOST=http://0.0.0.0:${WV_PORT}
      - WEAVIATE_CONFIG_PASSWORD=${WV_PASS}
      - QUERY_DEFAULTS_LIMIT: 20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      - PERSISTENCE_DATA_PATH: "./data"
      - DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      - ENABLE_MODULES: text2vec-transformers
      - TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      - CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ${WV_DIR}:/var/lib/weaviate

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      - ENABLE_CUDA: 0 
      # set to 1 to enable
      # - NVIDIA_VISIBLE_DEVICES: "all"
      # enable if running with CUDA

  # chatbot_api:
  #   container_name: chatbot_api
  #   depends_on:
  #     - crm_db
  #   build: .
  #   env_file: .env.dev
  #   ports:
  #     - "${WEB_PORT}:8000"  #Web port 
  #     - "${DBG_PORT}:4444"
  #   enviroment:
  #     - WEAVIATE_HOST=http://0.0.0.0:${WV_PORT}
  #     - WEAVIATE_CONFIG_PASSWORD=${WV_PASS}
        # - OPEN_API_KEY=${OPEN_API_KEY}
  #   # volume for hot-reloading!
  #   volumes:
  #     - .:/home/code

  #   #   - WEB_PORT=${WEB_PORT}
  #   restart: unless-stopped
  #   command: ["/home/code/entrypoint.sh"]
  #   # command: sh -c "python manage.py runserver 0.0.0.0:${WEB_PORT}"

