version: "3.4"

services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.19.2
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      OPENAI_APIKEY: $OPEN_AI_TOKEN
      WEAVIATE_HOST: "http://0.0.0.0:${WV_PORT}"
      WEAVIATE_CONFIG_PASSWORD: "${WV_PASS}"
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: text2vec-openai
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      CLUSTER_HOSTNAME: 'node1'
      LOG_LEVEL: 'debug'
      CLUSTER_HOSTNAME: 'node1'
      AUTOSCHEMA_ENABLED: 'true'
    volumes:
      - ${WV_DIR}:/var/lib/weaviate

  # chatbot_api:
  #   container_name: chatbot_api
  #   depends_on:
  #     - crm_db
  #   build: .
  #   env_file: .env.dev
  #   ports:
  #     - "${WEB_PORT}:8000"  #Web port 
  #     - "${DBG_PORT}:4444"
  #   enviroment:
  #     - WEAVIATE_HOST=http://0.0.0.0:${WV_PORT}
  #     - WEAVIATE_CONFIG_PASSWORD=${WV_PASS}
        # - OPEN_API_KEY=${OPEN_API_KEY}
  #   # volume for hot-reloading!
  #   volumes:
  #     - .:/home/code

  #   #   - WEB_PORT=${WEB_PORT}
  #   restart: unless-stopped
  #   command: ["/home/code/entrypoint.sh"]
  #   # command: sh -c "python manage.py runserver 0.0.0.0:${WEB_PORT}"

