version: "3.4"

services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.19.2
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      OPENAI_APIKEY: $OPENAI_API_KEY
      WEAVIATE_HOST: "http://0.0.0.0:${WV_PORT}"
      WEAVIATE_CONFIG_PASSWORD: "${WV_PASS}"
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      CLUSTER_HOSTNAME: 'node1'
      AUTOSCHEMA_ENABLED: 'true'
      CONTEXTIONARY_URL: contextionary:9999
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      ENABLE_MODULES: 'text2vec-contextionary,text-spellcheck,ref2vec-centroid'
      LOG_LEVEL: debug
    
    volumes:
      - ${WV_DIR}:/var/lib/weaviate

  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
      - 9999:9999

  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en

  chatbot_api:
    container_name: chatbot_api
    depends_on:
      - weaviate
    build: .
    env_file: .env.dev
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${DBG_PORT}:4444"
    environment:
      WEAVIATE_HOST: weaviate:8080
      WEAVIATE_CONFIG_PASSWORD: ${WV_PASS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/home/code
      - ./data/.cache/huggingface:/root/.cache/huggingface
      - ./data/.cache/torch:/root/.cache/torch

    restart: unless-stopped
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "${API_PORT}"]
